/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Agent
         * @description Run the agent for one turn and stream AG-UI events as SSE.
         */
        post: operations["run_agent_agent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List recent conversations with message counts.
         */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Return a single conversation with its full message history.
         */
        get: operations["get_conversation_api_conversations__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Favorites
         * @description Return all saved repositories.
         */
        get: operations["list_favorites_api_favorites_get"];
        put?: never;
        /**
         * Add Favorite
         * @description Save a repository to favorites (idempotent on full_name).
         */
        post: operations["add_favorite_api_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Favorites
         * @description Download all favorites as a CSV file.
         */
        get: operations["export_favorites_api_favorites_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{full_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Favorite
         * @description Remove a repository from favorites by full name (``owner/repo``).
         */
        delete: operations["remove_favorite_api_favorites__full_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Config
         * @description Return the resolved provider/model and the language filter choices.
         */
        get: operations["get_app_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMessage
         * @description An activity progress message emitted between chat messages.
         */
        ActivityMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "activity";
            /** Activitytype */
            activityType: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * AssistantMessage
         * @description An assistant message.
         */
        AssistantMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            /** Content */
            content?: string | null;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCall"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * AudioInputContent
         * @description An audio input content fragment.
         */
        AudioInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "audio";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BinaryInputContent
         * @description A deprecated binary payload reference in a multimodal user message.
         */
        BinaryInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Mimetype */
            mimeType: string;
            /** Id */
            id?: string | null;
            /** Url */
            url?: string | null;
            /** Data */
            data?: string | null;
            /** Filename */
            filename?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ConfigOut
         * @description Runtime configuration the SPA needs (no secrets).
         */
        ConfigOut: {
            /** Provider */
            provider: string;
            /** Model Name */
            model_name: string;
            /** Languages */
            languages: string[];
        };
        /**
         * Context
         * @description Additional context for the agent.
         */
        Context: {
            /** Description */
            description: string;
            /** Value */
            value: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ConversationDetail
         * @description Full conversation: metadata plus its messages.
         */
        ConversationDetail: {
            /** Thread Id */
            thread_id: string;
            /** Command */
            command: string;
            /** Model Name */
            model_name?: string | null;
            /** Summary */
            summary?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["MessageOut"][];
        };
        /**
         * ConversationSummary
         * @description Conversation metadata plus a message count (list view).
         */
        ConversationSummary: {
            /** Thread Id */
            thread_id: string;
            /** Command */
            command: string;
            /** Model Name */
            model_name?: string | null;
            /** Summary */
            summary?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * DeveloperMessage
         * @description A developer message.
         */
        DeveloperMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "developer";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DocumentInputContent
         * @description A document input content fragment.
         */
        DocumentInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FavoritesOut
         * @description The current set of saved repositories.
         */
        FavoritesOut: {
            /** Saved Repos */
            saved_repos?: components["schemas"]["SavedRepository"][];
        };
        /**
         * FunctionCall
         * @description Name and arguments of a function call.
         */
        FunctionCall: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageInputContent
         * @description An image input content fragment.
         */
        ImageInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentDataSource
         * @description Inline base64-encoded source.
         */
        InputContentDataSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "data";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentUrlSource
         * @description URL-referenced source.
         */
        InputContentUrlSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MessageOut
         * @description A single conversation message.
         */
        MessageOut: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /**
         * ReasoningMessage
         * @description A reasoning message containing the agent's internal reasoning process.
         */
        ReasoningMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "reasoning";
            /** Content */
            content: string;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ResumeEntry
         * @description A per-interrupt response in the resume array of a RunAgentInput.
         */
        ResumeEntry: {
            /** Interruptid */
            interruptId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "cancelled";
            /** Payload */
            payload?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RunAgentInput
         * @description Input for running an agent.
         */
        RunAgentInput: {
            /** Threadid */
            threadId: string;
            /** Runid */
            runId: string;
            /** Parentrunid */
            parentRunId?: string | null;
            /** State */
            state: unknown;
            /** Messages */
            messages: (components["schemas"]["DeveloperMessage"] | components["schemas"]["SystemMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["UserMessage"] | components["schemas"]["ToolMessage"] | components["schemas"]["ActivityMessage"] | components["schemas"]["ReasoningMessage"])[];
            /** Tools */
            tools: components["schemas"]["Tool"][];
            /** Context */
            context: components["schemas"]["Context"][];
            /** Forwardedprops */
            forwardedProps: unknown;
            /** Resume */
            resume?: components["schemas"]["ResumeEntry"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SavedRepository
         * @description Represents a saved/favorited repository.
         */
        SavedRepository: {
            /**
             * Full Name
             * @description e.g., 'owner/repo'
             */
            full_name: string;
            /** Url */
            url: string;
            /** Stars */
            stars: number;
            /**
             * Language
             * @default
             */
            language: string;
            /** Topics */
            topics?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at?: string;
        };
        /**
         * SavedRepositoryIn
         * @description Payload for saving a repository to favorites.
         */
        SavedRepositoryIn: {
            /**
             * Full Name
             * @description e.g., 'owner/repo'
             */
            full_name: string;
            /** Url */
            url: string;
            /**
             * Stars
             * @default 0
             */
            stars: number;
            /**
             * Language
             * @default
             */
            language: string;
            /** Topics */
            topics?: string[];
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * SystemMessage
         * @description A system message.
         */
        SystemMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TextInputContent
         * @description A text fragment in a multimodal user message.
         */
        TextInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Tool
         * @description A tool definition.
         */
        Tool: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolCall
         * @description A tool call, modelled after OpenAI tool calls.
         */
        ToolCall: {
            /** Id */
            id: string;
            /**
             * Type
             * @default function
             * @constant
             */
            type: "function";
            function: components["schemas"]["FunctionCall"];
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolMessage
         * @description A tool result message.
         */
        ToolMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /** Content */
            content: string;
            /** Toolcallid */
            toolCallId: string;
            /** Error */
            error?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UserMessage
         * @description A user message supporting text or multimodal content.
         */
        UserMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            /** Content */
            content: string | (components["schemas"]["TextInputContent"] | components["schemas"]["ImageInputContent"] | components["schemas"]["AudioInputContent"] | components["schemas"]["VideoInputContent"] | components["schemas"]["DocumentInputContent"] | components["schemas"]["BinaryInputContent"])[];
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoInputContent
         * @description A video input content fragment.
         */
        VideoInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_agent_agent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_favorites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesOut"];
                };
            };
        };
    };
    add_favorite_api_favorites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedRepositoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_favorites_api_favorites_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    remove_favorite_api_favorites__full_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
}
