"""Regenerate CLI documentation from the Typer app.

Writes the full command reference to `docs/cli.md` and injects a short
``name — one-line help`` list of registered commands into `README.md` between
``<!-- COMMANDS-START -->`` / ``<!-- COMMANDS-END -->`` markers.

Run via `uv run python scripts/update_cli_docs.py`. Pass `--check` to fail
(non-zero exit) if either file is out of date instead of rewriting it.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"
CLI_DOC_PATH = REPO_ROOT / "docs" / "cli.md"
TYPER_TARGET = "src/repo_research/main.py"
CLI_NAME = "repo-research"

COMMANDS_START = "<!-- COMMANDS-START -->"
COMMANDS_END = "<!-- COMMANDS-END -->"
GENERATED_NOTICE = (
    "<!-- Generated by `uv run python scripts/update_cli_docs.py` "
    "— do not edit by hand. -->"
)


def generate_cli_markdown() -> str:
    """Invoke `typer ... utils docs` and return the captured Markdown."""
    result = subprocess.run(
        ["uv", "run", "typer", TYPER_TARGET, "utils", "docs", "--name", CLI_NAME],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.rstrip() + "\n"


def render_commands_list() -> str:
    """Return a Markdown bullet list of ``name — help`` for every registered command.

    Imports the Typer app lazily so this module stays importable without the
    project's runtime dependencies.
    """
    from repo_research.main import app

    lines: list[str] = []
    for cmd in app.registered_commands:
        name = cmd.name or cmd.callback.__name__
        doc = (cmd.callback.__doc__ or "").strip().splitlines()
        summary = doc[0].strip() if doc else ""
        lines.append(f"- **`{name}`** — {summary}" if summary else f"- **`{name}`**")
    return "\n".join(lines) + "\n"


def update_readme(readme_text: str, commands_md: str) -> str:
    """Replace content between the COMMANDS markers in README text."""
    if COMMANDS_START not in readme_text or COMMANDS_END not in readme_text:
        raise SystemExit(
            f"README is missing {COMMANDS_START!r} / {COMMANDS_END!r} markers; "
            "add them before running this script."
        )
    block = f"{COMMANDS_START}\n{GENERATED_NOTICE}\n\n{commands_md}\n{COMMANDS_END}"
    pattern = re.compile(
        re.escape(COMMANDS_START) + r".*?" + re.escape(COMMANDS_END),
        flags=re.DOTALL,
    )
    return pattern.sub(block, readme_text, count=1)


def write_if_changed(path: Path, new_content: str, *, check: bool) -> bool:
    """Write `new_content` to `path` (or report drift in check mode).

    Returns True when the file content matched, False when it differed.
    """
    current = path.read_text() if path.exists() else ""
    if current == new_content:
        return True
    if check:
        print(
            f"::error:: {path.relative_to(REPO_ROOT)} is out of date.", file=sys.stderr
        )
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_content)
    print(f"updated {path.relative_to(REPO_ROOT)}")
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs are out of date instead of writing.",
    )
    args = parser.parse_args()

    cli_markdown = generate_cli_markdown()
    commands_md = render_commands_list()
    new_readme = update_readme(README_PATH.read_text(), commands_md)

    cli_doc_ok = write_if_changed(CLI_DOC_PATH, cli_markdown, check=args.check)
    readme_ok = write_if_changed(README_PATH, new_readme, check=args.check)

    if args.check and not (cli_doc_ok and readme_ok):
        print(
            "Run `uv run python scripts/update_cli_docs.py` and commit the changes.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
