"""Regenerate CLI documentation from the Typer app.

Writes the full command reference to `docs/cli.md` and injects the same content
into `README.md` between `<!-- CLI-DOCS-START -->` / `<!-- CLI-DOCS-END -->`
markers.

Run via `uv run python scripts/update_cli_docs.py`. Pass `--check` to fail
(non-zero exit) if either file is out of date instead of rewriting it.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"
CLI_DOC_PATH = REPO_ROOT / "docs" / "cli.md"
TYPER_TARGET = "src/github_agent/main.py"
CLI_NAME = "github-agent"

START_MARKER = "<!-- CLI-DOCS-START -->"
END_MARKER = "<!-- CLI-DOCS-END -->"
GENERATED_NOTICE = (
    "<!-- Generated by `uv run python scripts/update_cli_docs.py` "
    "— do not edit by hand. -->"
)


def generate_cli_markdown() -> str:
    """Invoke `typer ... utils docs` and return the captured Markdown."""
    result = subprocess.run(
        ["uv", "run", "typer", TYPER_TARGET, "utils", "docs", "--name", CLI_NAME],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.rstrip() + "\n"


def shift_headings(markdown: str) -> str:
    """Demote every Markdown heading by one level so it nests under a README H2."""
    return re.sub(r"^(#{1,5}) ", r"#\1 ", markdown, flags=re.MULTILINE)


def render_readme_section(cli_markdown: str) -> str:
    """Return the block to splice between the README markers."""
    shifted = shift_headings(cli_markdown)
    return f"\n{GENERATED_NOTICE}\n\n{shifted}\n"


def update_readme(readme_text: str, cli_markdown: str) -> str:
    """Replace content between the CLI-DOCS markers in README text."""
    if START_MARKER not in readme_text or END_MARKER not in readme_text:
        raise SystemExit(
            f"README is missing {START_MARKER!r} / {END_MARKER!r} markers; "
            "add them before running this script."
        )
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        flags=re.DOTALL,
    )
    replacement = START_MARKER + render_readme_section(cli_markdown) + END_MARKER
    return pattern.sub(replacement, readme_text, count=1)


def write_if_changed(path: Path, new_content: str, *, check: bool) -> bool:
    """Write `new_content` to `path` (or report drift in check mode).

    Returns True when the file content matched, False when it differed.
    """
    current = path.read_text() if path.exists() else ""
    if current == new_content:
        return True
    if check:
        print(
            f"::error:: {path.relative_to(REPO_ROOT)} is out of date.", file=sys.stderr
        )
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_content)
    print(f"updated {path.relative_to(REPO_ROOT)}")
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs are out of date instead of writing.",
    )
    args = parser.parse_args()

    cli_markdown = generate_cli_markdown()
    new_readme = update_readme(README_PATH.read_text(), cli_markdown)

    readme_ok = write_if_changed(README_PATH, new_readme, check=args.check)
    cli_doc_ok = write_if_changed(CLI_DOC_PATH, cli_markdown, check=args.check)

    if args.check and not (readme_ok and cli_doc_ok):
        print(
            "Run `uv run python scripts/update_cli_docs.py` and commit the changes.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
