"""Markdown export utilities for hotspot analysis results.

Provides strongly-typed export functionality to generate markdown reports
from hotspot analysis data and LLM conversation history.
"""

from pathlib import Path

from langchain_core.messages import AIMessage

from integrations.github.models import FileHotspot, HotspotAnalysisResult

from ..models import ExportMetadata


def format_hotspot_table(hotspots: list[FileHotspot]) -> str:
    """Format hotspot data as a markdown table.

    Args:
        hotspots: List of file hotspots to format

    Returns:
        Markdown table string
    """
    if not hotspots:
        return "_No hotspots found matching the criteria._\n"

    # Table header
    lines = [
        (
            "| File Path | Changes | Additions | Deletions | Churn Score "
            "| Authors | First Changed | Last Changed |"
        ),
        (
            "|-----------|---------|-----------|-----------|-------------|"
            "---------|---------------|--------------|"
        ),
    ]

    # Table rows
    for hotspot in hotspots:
        first_changed = (
            hotspot.first_changed.strftime("%Y-%m-%d")
            if hotspot.first_changed
            else "N/A"
        )
        last_changed = (
            hotspot.last_changed.strftime("%Y-%m-%d") if hotspot.last_changed else "N/A"
        )

        # Format churn score based on type (handle both int and float)
        if isinstance(hotspot.churn_score, float):
            churn_str = f"{hotspot.churn_score:.2f}"
        else:
            churn_str = str(hotspot.churn_score)

        row = (
            f"| `{hotspot.file_path}` | {hotspot.change_count} | "
            f"{hotspot.total_additions} | {hotspot.total_deletions} | "
            f"{churn_str} | {hotspot.unique_authors} | "
            f"{first_changed} | {last_changed} |"
        )
        lines.append(row)

    return "\n".join(lines) + "\n"


# Note: we need to preserve type info/full data to be able to use this
def format_analysis_summary(
    result: HotspotAnalysisResult, strategy: str = "activity"
) -> str:
    """Format analysis summary section.

    Args:
        result: Complete hotspot analysis result
        strategy: Churn calculation strategy used

    Returns:
        Formatted summary string
    """
    start_date = result.date_range_start.strftime("%Y-%m-%d")
    end_date = result.date_range_end.strftime("%Y-%m-%d")

    summary = (
        f"**Analysis Period:** {result.analysis_period_days} days "
        f"({start_date} to {end_date})\n"
        f"**Total Commits Analyzed:** {result.total_commits_analyzed}\n"
        f"**Total Files Changed:** {result.total_files_changed}\n"
        f"**Strategy:** {strategy}\n"
    )

    if result.path_filter:
        summary += f"**Path Filter:** `{result.path_filter}`\n"

    return summary


def generate_markdown_report(
    metadata: ExportMetadata,
    analysis_message: AIMessage,
    strategy: str = "activity",
    days: int = 90,
    max_commits: int = 200,
    min_changes: int = 3,
    path_filter: str | None = None,
) -> str:
    """Generate complete markdown report.

    Args:
        metadata: Export metadata (repo name, date, sha, etc.)
        result: Hotspot analysis result data
        messages: Conversation messages to include
        strategy: Churn calculation strategy used
        days: Number of days analyzed
        max_commits: Maximum commits analyzed
        min_changes: Minimum changes threshold
        path_filter: Optional path filter applied

    Returns:
        Complete markdown document string
    """
    analysis_date_str = metadata.analysis_date.strftime("%d-%m-%Y %H:%M")

    # Build the document sections
    document = f"""# Hotspot Analysis: {metadata.repo_name}

**Analysis Date:** {analysis_date_str}

**Commit SHA:** {
        metadata.latest_commit_sha if metadata.latest_commit_sha is not None else "N/A"
    }

## Parameters

- **Days:** {days}
- **Max Commits:** {max_commits}
- **Min Changes:** {min_changes}
- **Path Filter:** {path_filter or "All files"}
- **Strategy:** {strategy}

## Analysis & Insights

{analysis_message.content}

---

_Report generated by github-agent at {metadata.analysis_date.isoformat()}_
"""

    return document


def write_to_file(content: str, filepath: Path) -> None:
    """Write markdown content to file.

    Args:
        content: Markdown content to write
        filepath: Path to output file

    Raises:
        OSError: If unable to create directory or write file
    """
    # Ensure output directory exists
    filepath.parent.mkdir(parents=True, exist_ok=True)

    # Write content to file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
